---
platform: linux

inputs:
- name: git-pipeline
- name: git-user
  optional: true
- name: git-orders
  optional: true
- name: git-carts
  optional: true
#- name: current-app-info

outputs:
- name: prepared-release

run:
  user: root
  path: ./git-pipeline/deploy/cloud-foundry/ci/tasks/prepare-release