apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sock-shop
  namespace: sock-shop
spec:
  hosts:
  - "*"
  gateways:
  - front-end-gateway
  http:
  - match:
    - headers:
        host:
          exact: "user.35.241.201.68.nip.io"
    route:
    - destination:
        port:
          number: 80
        host: user
