apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sock-shop
  namespace: sock-shop
spec:
  hosts:
  - "*"
  gateways:
  - front-end-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    - headers:
        host:
          prefix: "user"
    route:
    - destination:
        port:
          number: 80
        host: user
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 8079
        host: front-end
