---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  metadata:
    name: rabbitmq
    app: rabbitmq
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        name: rabbitmq
        version: v1
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.8-management
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
              - DAC_OVERRIDE
          readOnlyRootFilesystem: true
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    name: rabbitmq
  namespace: sock-shop
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 9090
    name: exporter
    protocol: TCP
  selector:
    app: rabbitmq
    name: rabbitmq

